# Change these first
owner: clirdlf # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: CLIR
    url: https://www.clir.org
  - name: DLF
    url: https://www.diglib.org
  - name: DLF Wiki
    url: https://wiki.diglib.org
  - name: Jobs
    url: https://jobs.diglib.org
  - name: Hidden Collections Africa
    url: https://hiddencollections.africa
  - name: Climate Resiliency
    url: https://climate-resiliancy.clir.org
  - name: Digital Conferences Calendar
    url: https://digital-conferences-calendar.info
  - name: Endangered Data Week
    url: https://endangereddataweek.org
  - name: IJA
    url: https://ijarchive.org
  - name: Leading Change Institute
    url: https://leadingchangeinstitute.org
  - name: NDSA
    url: https://ndsa.org
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.clir.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/clirdlf/climate-resiliancy.clir.org/main/src/assets/images/logo.png
  name: CLIR Uptime Monitor
  introTitle: "**CLIR** website uptime monitor and status page"
  introMessage: This status page uses **real-time** data from our [GitHub repository](https://github.com/clirdlf/uptime). [**Check out our content**](https://www.clir.org)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
